### ISSUE TITLE
Deadlock in Natron when handling Transform node

### ISSUE THREAD

**Issue by StepanDav** [MrKepzie/Natron#708]
Natron v2.0.0 from git branch workshop commit 446924897c75e7a911399a8d553e9d0b27c40809  for   Linux 64bit; official snapshot build.

When manipulating with Transform node, non-deterministically, Natron freezes. This looks like a deadlock within Node.cpp, where "_imp->inputsMutex" is held. The stack trace of thread #1 suggests that this commit has introduced the deadlock: https://github.com/MrKepzie/Natron/commit/f8a85a922ba298b00956a939df9706a303718097

Stack trace for each thread:
```
$ gdb /opt/NatronSnapshot/bin/Natron.debug 
GNU gdb (GDB) 7.6.2 (Debian 7.6.2-1.1+b1)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /opt/NatronSnapshot/bin/Natron.debug...(no debugging symbols found)...done.
(gdb) attach 15654
Attaching to program: /opt/NatronSnapshot/bin/Natron.debug, process 15654
[...crapton of shared libraries loaded...]
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f1536f964bc in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#2  0x00007f1536f92145 in QMutex::lockInternal() () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#3  0x0000000000b8d150 in Natron::Node::getInput(int) const ()
#4  0x0000000000b92a90 in Natron::Node::computeHashInternal(std::list<Natron::Node*, std::allocator<Natron::Node*> >&) ()
#5  0x0000000000b92c7a in Natron::Node::computeHash() ()
#6  0x0000000000b92d1d in Natron::Node::incrementKnobsAge() ()
#7  0x00000000009e3a66 in Natron::EffectInstance::abortAnyEvaluation() ()
#8  0x0000000000ba5eaa in Natron::Node::connectInput(boost::shared_ptr<Natron::Node> const&, int) ()
#9  0x0000000000bc3546 in NodeCollection::connectNodes(int, boost::shared_ptr<Natron::Node> const&, Natron::Node*, bool) ()
#10 0x0000000000768035 in ConnectCommand::doConnect(boost::shared_ptr<Natron::Node> const&, boost::shared_ptr<Natron::Node> const&) ()
#11 0x0000000000768263 in ConnectCommand::redo() ()
#12 0x00007f1537f52d73 in QUndoStack::push(QUndoCommand*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#13 0x00000000007479dc in NodeGraph::mouseReleaseEvent(QMouseEvent*) ()
#14 0x00007f1537952c9c in QWidget::event(QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#15 0x00007f1537ce7e36 in QFrame::event(QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#16 0x00007f1537f10d7b in QGraphicsView::viewportEvent(QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#17 0x00007f1537093207 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#18 0x00007f1537904cfc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#19 0x00007f153790bdf8 in QApplication::notify(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#20 0x00007f153709395c in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#21 0x00007f1537909a2e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#22 0x00007f153798006b in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#23 0x00007f153797ea08 in QApplication::x11ProcessEvent(_XEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#24 0x00007f15379a8742 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#25 0x00007f1534fc6c3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007f1534fc6f20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f1534fc6fcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f15370c0b43 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#29 0x00007f15379a82de in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#30 0x00007f1537092642 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#31 0x00007f15370929a4 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#32 0x00007f15370981eb in QCoreApplication::exec() () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#33 0x00000000006e1a27 in main ()
(gdb) info threads
  Id   Target Id         Frame 
  8    Thread 0x7f1522230700 (LWP 15655) "Thread (pooled)" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7f1521a2f700 (LWP 15656) "ViewerCurrentFr" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7f152122e700 (LWP 15657) "ViewerCurrentFr" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7f1512bfd700 (LWP 15967) "QInotifyFileSys" 0x00007f1535ec790d in poll () at ../sysdeps/unix/syscall-template.S:81
  4    Thread 0x7f15123fc700 (LWP 15968) "QInotifyFileSys" 0x00007f1535ec790d in poll () at ../sysdeps/unix/syscall-template.S:81
  3    Thread 0x7f1513bff700 (LWP 15969) "CacheDeleter" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7f15133fe700 (LWP 15970) "CacheDeleter" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 1    Thread 0x7f153a5f7940 (LWP 15654) "Natron.debug" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
(gdb) thread 2
[Switching to thread 2 (Thread 0x7f15133fe700 (LWP 15970))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f1536f9823b in QWaitCondition::wait(QMutex*, unsigned long) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#2  0x00000000009c12d2 in Natron::DeleterThread<Natron::Image>::run() ()
#3  0x00007f1536f97a32 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#4  0x00007f15369c4062 in start_thread (arg=0x7f15133fe700) at pthread_create.c:312
#5  0x00007f1535ed2c1d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) thread 3
[Switching to thread 3 (Thread 0x7f1513bff700 (LWP 15969))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f1536f9823b in QWaitCondition::wait(QMutex*, unsigned long) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#2  0x00000000009c14f2 in Natron::DeleterThread<Natron::FrameEntry>::run() ()
#3  0x00007f1536f97a32 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#4  0x00007f15369c4062 in start_thread (arg=0x7f1513bff700) at pthread_create.c:312
#5  0x00007f1535ed2c1d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) thread 4
[Switching to thread 4 (Thread 0x7f15123fc700 (LWP 15968))]
#0  0x00007f1535ec790d in poll () at ../sysdeps/unix/syscall-template.S:81
81	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007f1535ec790d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f1534fc6ebc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f1534fc6fcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f15370c0b96 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#4  0x00007f1537092642 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#5  0x00007f15370929a4 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#6  0x00007f1536f94e7f in QThread::exec() () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#7  0x00007f1537071cb8 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#8  0x00007f1536f97a32 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#9  0x00007f15369c4062 in start_thread (arg=0x7f15123fc700) at pthread_create.c:312
#10 0x00007f1535ed2c1d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) thread 5
[Switching to thread 5 (Thread 0x7f1512bfd700 (LWP 15967))]
#0  0x00007f1535ec790d in poll () at ../sysdeps/unix/syscall-template.S:81
81	in ../sysdeps/unix/syscall-template.S
(gdb) bt
#0  0x00007f1535ec790d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f1534fc6ebc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f1534fc6fcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f15370c0b96 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#4  0x00007f1537092642 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#5  0x00007f15370929a4 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#6  0x00007f1536f94e7f in QThread::exec() () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#7  0x00007f1537071cb8 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#8  0x00007f1536f97a32 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#9  0x00007f15369c4062 in start_thread (arg=0x7f1512bfd700) at pthread_create.c:312
#10 0x00007f1535ed2c1d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) thread 6
[Switching to thread 6 (Thread 0x7f152122e700 (LWP 15657))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f1536f9823b in QWaitCondition::wait(QMutex*, unsigned long) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#2  0x00007f1536f931af in QReadWriteLock::lockForRead() () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#3  0x0000000000b8aea8 in Natron::Node::getHashValue() const ()
#4  0x0000000000bbf3cd in NodeCollection::setParallelRenderArgs(int, int, bool, bool, bool, unsigned long, Natron::OutputEffectInstance*, int, TimeLine const*, boost::shared_ptr<Natron::Node> const&, bool) ()
#5  0x0000000000bc3bc6 in ParallelRenderArgsSetter::ParallelRenderArgsSetter(NodeCollection*, int, int, bool, bool, bool, unsigned long, Natron::OutputEffectInstance*, int, TimeLine const*, boost::shared_ptr<Natron::Node> const&, bool) ()
#6  0x0000000000cf0589 in ViewerParallelRenderArgsSetter::ViewerParallelRenderArgsSetter(NodeCollection*, int, int, bool, bool, bool, unsigned long, Natron::OutputEffectInstance*, int, TimeLine const*, bool, boost::shared_ptr<Natron::Node> const&, boost::shared_ptr<RotoStrokeItem> const&, boost::shared_ptr<Natron::Node> const&) [clone .clone.2] ()
#7  0x0000000000cf55e6 in ViewerInstance::renderViewer_internal(int, bool, bool, unsigned long, bool, boost::shared_ptr<Natron::Node>, bool, boost::shared_ptr<RequestedFrame> const&, ViewerArgs&) ()
#8  0x0000000000cf6679 in ViewerInstance::renderViewer(int, bool, bool, unsigned long, bool, boost::shared_ptr<Natron::Node> const&, bool, boost::shared_ptr<ViewerArgs>*, boost::shared_ptr<RequestedFrame> const&) ()
#9  0x0000000000c2f086 in renderCurrentFrameFunctor(CurrentFrameFunctorArgs&) ()
#10 0x0000000000c32b29 in ViewerCurrentFrameRequestRendererBackup::run() ()
#11 0x00007f1536f97a32 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#12 0x00007f15369c4062 in start_thread (arg=0x7f152122e700) at pthread_create.c:312
#13 0x00007f1535ed2c1d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) thread 7
[Switching to thread 7 (Thread 0x7f1521a2f700 (LWP 15656))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f1536f9823b in QWaitCondition::wait(QMutex*, unsigned long) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#2  0x0000000000c3355a in ViewerCurrentFrameRequestScheduler::run() ()
#3  0x00007f1536f97a32 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#4  0x00007f15369c4062 in start_thread (arg=0x7f1521a2f700) at pthread_create.c:312
#5  0x00007f1535ed2c1d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) thread 8
[Switching to thread 8 (Thread 0x7f1522230700 (LWP 15655))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	in ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f1536f9823b in QWaitCondition::wait(QMutex*, unsigned long) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#2  0x00007f1536f8b6ec in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#3  0x00007f1536f97a32 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#4  0x00007f15369c4062 in start_thread (arg=0x7f1522230700) at pthread_create.c:312
#5  0x00007f1535ed2c1d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by StepanDav** [comment]
By the way, this would be preventable by static analysis of locking. You may be interested in https://bugreports.qt.io/browse/QTBUG-46784
