### ISSUE TITLE
Please build a binary with debug symbols with snapshot builds

### ISSUE THREAD

**Issue by StepanDav** [MrKepzie/Natron#709]
It would make debugging much easier if I could attach gdb and just see exactly the line numbers where crashes happen. It's totally fine if the binary with debug symbols would be a separate download and not part of the main bundle, but it would be incredibly useful to have it :)

**Comment by MrKepzie** [comment]
There is one already, just start Natron -debug in a terminal

**Comment by StepanDav** [comment]
Alas, it lacks sufficient amount of debug symbols to provide line numbers.

I've just replicated the crash in #707  with GDB attached, and all I got was this t-shirt^W stack trace:
```
(gdb) bt
#0  0x00007faf53c83def in ?? () from /opt/NatronSnapshot/Plugins/Misc.ofx.bundle/Contents/Linux-x86-64/Misc.ofx
#1  0x00007faf53b1913f in ?? () from /opt/NatronSnapshot/Plugins/Misc.ofx.bundle/Contents/Linux-x86-64/Misc.ofx
#2  0x00007faf53c7af81 in ?? () from /opt/NatronSnapshot/Plugins/Misc.ofx.bundle/Contents/Linux-x86-64/Misc.ofx
#3  0x0000000000d7bf23 in OFX::Host::ImageEffect::Instance::mainEntry(char const*, void const*, OFX::Host::Property::Set*, OFX::Host::Property::Set*) ()
#4  0x0000000000beeed8 in Natron::OfxImageEffectInstance::mainEntry(char const*, void const*, OFX::Host::Property::Set*, OFX::Host::Property::Set*) ()
#5  0x0000000000d7cf52 in OFX::Host::ImageEffect::Instance::getRegionOfDefinitionAction(double, OfxPointD, int, OfxRectD&) ()
#6  0x0000000000c02d21 in OfxEffectInstance::createOfxImageEffectInstance(OFX::Host::ImageEffect::ImageEffectPlugin*, OFX::Host::ImageEffect::Descriptor*, Natron::ContextEnum, NodeSerialization const*, std::list<boost::shared_ptr<KnobSerialization>, std::allocator<boost::shared_ptr<KnobSerialization> > > const&, bool, bool) ()
#7  0x0000000000be4b81 in Natron::OfxHost::createOfxEffect(boost::shared_ptr<Natron::Node>, NodeSerialization const*, std::list<boost::shared_ptr<KnobSerialization>, std::allocator<boost::shared_ptr<KnobSerialization> > > const&, bool, bool) ()
#8  0x0000000000999d65 in AppManager::createOFXEffect(boost::shared_ptr<Natron::Node>, NodeSerialization const*, std::list<boost::shared_ptr<KnobSerialization>, std::allocator<boost::shared_ptr<KnobSerialization> > > const&, bool, bool) const ()
#9  0x0000000000bb3f45 in Natron::Node::load(std::string const&, NodeSerialization const&, bool, bool, bool, QString const&, std::list<boost::shared_ptr<KnobSerialization>, std::allocator<boost::shared_ptr<KnobSerialization> > > const&) ()
#10 0x0000000000990def in AppInstance::createNodeInternal(QString const&, std::string const&, int, int, bool, NodeSerialization const&, bool, bool, double, double, bool, bool, bool, bool, QString const&, std::list<boost::shared_ptr<KnobSerialization>, std::allocator<boost::shared_ptr<KnobSerialization> > > const&, boost::shared_ptr<NodeCollection> const&) ()
#11 0x0000000000992ba8 in AppInstance::createNode(CreateNodeArgs const&) ()
#12 0x00000000007bc826 in ToolButton::onTriggered() ()
#13 0x00007faf716715b1 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#14 0x00007faf71ec7dd2 in QAction::triggered(bool) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#15 0x00007faf71ec91db in QAction::activate(QAction::ActionEvent) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#16 0x00007faf722ec189 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#17 0x00007faf722f186a in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#18 0x00007faf71f1bc9c in QWidget::event(QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#19 0x00007faf722f38ab in QMenu::event(QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#20 0x00007faf71ecdd2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#21 0x00007faf71ed4df8 in QApplication::notify(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#22 0x00007faf7165c95c in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#23 0x00007faf71ed2a2e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#24 0x00007faf71f494fd in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#25 0x00007faf71f47a08 in QApplication::x11ProcessEvent(_XEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#26 0x00007faf71f71742 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#27 0x00007faf6f58fc3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007faf6f58ff20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007faf6f58ffcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007faf71689b96 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#31 0x00007faf71f712de in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#32 0x00007faf7165b642 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#33 0x00007faf7165b9a4 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#34 0x00007faf722ef475 in QMenu::exec(QPoint const&, QAction*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#35 0x000000000075cbbb in NodeGraph::showMenu(QPoint const&) ()
#36 0x000000000075e1ce in NodeGraph::mousePressEvent(QMouseEvent*) ()
#37 0x00007faf71f1bc83 in QWidget::event(QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#38 0x00007faf722b0e36 in QFrame::event(QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#39 0x00007faf724d9d7b in QGraphicsView::viewportEvent(QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#40 0x00007faf7165c207 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#41 0x00007faf71ecdcfc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#42 0x00007faf71ed4df8 in QApplication::notify(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#43 0x00007faf7165c95c in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#44 0x00007faf71ed2a2e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#45 0x00007faf71f4906b in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#46 0x00007faf71f47a08 in QApplication::x11ProcessEvent(_XEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#47 0x00007faf71f71742 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#48 0x00007faf6f58fc3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007faf6f58ff20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#50 0x00007faf6f58ffcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#51 0x00007faf71689b43 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#52 0x00007faf71f712de in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#53 0x00007faf7165b642 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#54 0x00007faf7165b9a4 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#55 0x00007faf716611eb in QCoreApplication::exec() () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#56 0x00000000006e1a27 in main ()
```

What I expected are actual line number, as what I get with an unstripped binary compiled with -g (on GCC/Clang).

Upon reflection, you also probably want the plugins to be built with debug symbols as well, not just the binary itself, given that a lot of the stuff is likely plugin <-> Natron interaction...

**Comment by MrKepzie** [comment]
You are true, though this brings some changes to the build system. We might do it anyway one day since we are going to introduce google-breakpad crash reporter support (client side is already implemented).
I don't need much more backtrace to see where it fails anyway, will try to reproduce it on a linux box

**Comment by StepanDav** [comment]
Is there any chance I could convince you to reconsider? I'm saying this because:
1) I keep filing substantial amount of bugs any time I try a new snapshot, which could be more quickly resolved with more debugging information.
2) Natron (and the openfx modules) have many dependencies, making build non-trivial and very environment-sensitive.
3) The amount of change to build system seems trivial at face value -- just build the binary and modules with additional -g flag, and avoid stripping binaries.

If the timeline for google-breakpad is "next week", then it probably doesn't make sense, but if it's any longer than that I feel the benefits outweigh the drawbacks...

**Comment by olear** [comment]
Breakpad support is not next week, but maybe next month (I need to setup the server stuff). Changing the build system and installer to include (more) debug binaries of Natron and plugins are doable, but takes time (that could be used for other things, the installer is not perfect etc etc).

Building Natron+plugins is not that hard, most modern distros have all depends already.

**Comment by StepanDav** [comment]
And, at the risk of beating a dead horse, what about using -g by default, thus avoiding any mess with adding new build target? The increase in binary size is certainly not tragic (especially if you consider the target market is video processing), the benefits are there?

(I promise I'll give up after this one:) )

**Comment by devernay** [comment]
just wait for google breakpad. With breakpad, the binaries are distributed without debugging symbols , which stay on the server. Due to heavy use of templates in both Natron and the plugins, debugging symbols are huge.

**Comment by StepanDav** [comment]
Sounds fair, thanks!:)
