### ISSUE TITLE
Segfault when attempting to edit ColorLookup curve

### ISSUE THREAD

**Issue by StepanDav** [MrKepzie/Natron#722]
"Natron v2.0.0 from git branch workshop commit ba3497891f784588bb079e5e9cfc2c500cfac32f  for   Linux 64bit", official snapshot download.

Steps to reproduce:
1) Create ColorLookup node.
2) Double-click on it.
3) Segfault.

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000009dd1de in Curve::addKeyFrame(KeyFrame) ()
(gdb) bt
#0  0x00000000009dd1de in Curve::addKeyFrame(KeyFrame) ()
#1  0x0000000000b695cc in Knob<double>::onKeyFrameSet(int, KeyFrame const&, int) ()
#2  0x00000000008d95be in KnobGui::setKeyframes(std::vector<KeyFrame, std::allocator<KeyFrame> > const&, int) ()
#3  0x00000000009863f1 in AddKeysCommand::addOrRemoveKeyframe(bool, bool) ()
#4  0x00007fc893faed73 in QUndoStack::push(QUndoCommand*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#5  0x0000000000840150 in CurveWidget::mouseDoubleClickEvent(QMouseEvent*) ()
#6  0x00007fc8939aecb5 in QWidget::event(QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#7  0x00007fc894468dbc in QGLWidget::event(QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtOpenGL.so.4
#8  0x00007fc893960d2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#9  0x00007fc893967df8 in QApplication::notify(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#10 0x00007fc8930ef95c in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#11 0x00007fc893965a2e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#12 0x00007fc8939dc06b in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#13 0x00007fc8939daa08 in QApplication::x11ProcessEvent(_XEvent*) () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#14 0x00007fc893a04742 in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#15 0x00007fc891022c3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007fc891022f20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007fc891022fcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007fc89311cb43 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#19 0x00007fc893a042de in ?? () from /opt/NatronSnapshot/bin/../lib/libQtGui.so.4
#20 0x00007fc8930ee642 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#21 0x00007fc8930ee9a4 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#22 0x00007fc8930f41eb in QCoreApplication::exec() () from /opt/NatronSnapshot/bin/../lib/libQtCore.so.4
#23 0x00000000006e1a57 in main ()
(gdb) info threads
  Id   Target Id         Frame 
  4    Thread 0x7fc88072e700 (LWP 3900) "ViewerCurrentFr" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7fc87ff2d700 (LWP 3901) "ViewerCurrentFr" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7fc87cba9700 (LWP 3902) "Thread (pooled)" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 1    Thread 0x7fc896653940 (LWP 3899) "Natron.debug" 0x00000000009dd1de in Curve::addKeyFrame(KeyFrame) ()
(gdb) f 0
#0  0x00000000009dd1de in Curve::addKeyFrame(KeyFrame) ()
```

**Comment by olear** [comment]
Seems to work here on latest snapshot ...
![screenshot-3](https://cloud.githubusercontent.com/assets/7461595/8488591/fcb506e0-2113-11e5-9944-bef4f3b90e4d.png)

**Comment by StepanDav** [comment]
ACK, will retry with most recent snapshot.

**Comment by StepanDav** [comment]
I can confirm this still crashes at 40210cc9af33f4d554d14a5dd56ec8bc76fb9bdc.

But I messed up the steps to reproduce. Double click on the curve graph, specifically.

**Comment by olear** [comment]
Can't reproduce on my version, will clean and test the same version as you are using.
![screenshot-4](https://cloud.githubusercontent.com/assets/7461595/8488724/28b508ac-2115-11e5-9fab-8fbaaa5bc541.png)
